language: node_js
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
      node_js:
        - "6"
        - "8"
    - stage: deploy
      script: bash ./travis/deploy.sh
      node_js:
        - "8"
      env:
        - ENCRYPTION_LABEL: "9d936859ef00"
        - COMMIT_AUTHOR_EMAIL: "rocket0191@gmail.com"
dist: trusty
sudo: false
